export const texts = {
  es: {
    recipeBook: "Recetario 007",
    favorites: "Favoritos",
    home: "Inicio",
    filters: "Filtros",
    sinFavoritos: "No existen favoritos para mostrar.",
    noReceta: "Cargando recetas...",
    error: "Error al cargar la información...",
    description: "Descripción",
    gluten: "Sin gluten",
    preparation: "Preparación",
    noInfo: "No existe información disponible",
    notFoundTitle: "Página no encontrada",
    notFoundMessage: "Parece que te has perdido buscando ingredientes.",
    backToHome: "Volver al inicio",
    loginTitle: "Iniciar Sesión",
    emailLabel: "Correo Electrónico",
    passwordLabel: "Contraseña",
    loginButton: "Ingresar",
    logoutQuestion: "¿Deseas cerrar sesión?",
    confirmYes: "Sí",
    confirmNo: "No",
    placeHolder: {
      titulo: "Titulo",
      ingredientes: "Ingredientes",
      todo: "Todos",
      vegano: "Vegano",
      vegetariano: "Vegetariano",
      carneRoja: "Carnes rojas",
      carneBlanca: "Carnes blancas",
      tiempo: "Tiempo (min)",
      porciones: "Porciones",
      limpiar: "Limpiar filtros",
      notFoundTitle: "Página no encontrada",
      notFoundMessage: "Parece que te has perdido buscando ingredientes.",
      backToHome: "Volver al inicio",
      email: "ejemplo@correo.com",
      password: "Tu contraseña",
    },
  },
  en: {
    recipeBook: "Recipe Book 007",
    favorites: "Favorites",
    home: "Home",
    filters: "Filters",
    sinFavoritos: "There are no favorites to show.",
    noReceta: "Loading recipes...",
    error: "Error loading information...",
    description: "Description",
    gluten: "Free gluten",
    preparation: "Preparation",
    noInfo: "No information available",
    notFoundTitle: "Page Not Found",
    notFoundMessage: "It seems you got lost looking for ingredients.",
    backToHome: "Back to home",
    loginTitle: "Login",
    emailLabel: "Email Address",
    passwordLabel: "Password",
    loginButton: "Sign In",
    logoutQuestion: "Do you want to log out?",
    confirmYes: "Yes",
    confirmNo: "No",
    placeHolder: {
      titulo: "Title",
      ingredientes: "Ingredients",
      todo: "All",
      vegano: "Vegan",
      vegetariano: "Vegetarian",
      carneRoja: "Red Meat",
      carneBlanca: "White Meat",
      tiempo: "Time (min)",
      porciones: "Portions",
      limpiar: "Clean filters",
      notFoundTitle: "Not found",
      notFoundMessage: "It seems you got lost looking for ingredients.",
      backToHome: "Back to top",
      email: "example@mail.com",
      password: "Your password",
    },
  },
};
