export const texts = {
  es: {
    loading: "Cocinando recetas",
    recipeBook: "Recetario 007",
    favorites: "Favoritos",
    home: "Inicio",
    filters: "Filtros",
    sinFavoritos: "No existen favoritos para mostrar.",
    noReceta: "Cargando recetas...",
    error: "Error al cargar la información...",
    description: "Descripción",
    gluten: "Sin gluten",
    preparation: "Preparación",
    noInfo: "No existe información disponible",
    notFoundTitle: "Página no encontrada",
    notFoundMessage: "Parece que te has perdido buscando ingredientes.",
    backToHome: "Volver al inicio",
    createRecipe: "Crear Nueva Receta",
    editRecipe: "Editar Receta",
    loginTitle: "Iniciar Sesión",
    emailLabel: "Correo Electrónico",
    passwordLabel: "Contraseña",
    loginButton: "Ingresar",
    noPass: "¿Olvidaste tu contraseña?",
    logoutQuestion: "¿Deseas cerrar sesión?",
    confirmYes: "Sí",
    confirmNo: "No",
    registerButton: "Registrarme",
    noCuenta: "¿No tenés cuenta?",
    siCuenta: "¿Tenés cuenta?",
    createAccount: "Crear",
    notAccess: "Acceso restringido",
    messAccess: "Para hacer eso, por favor inicia sesión",
    messRol:"Tu usuario no tiene los privilegios necesarios para ver esta página",
    placeHolder: {
      titulo: "Titulo",
      ingredientes: "Ingredientes",
      todo: "Todos",
      vegano: "Vegano",
      vegetariano: "Vegetariano",
      carneRoja: "Carnes rojas",
      carneBlanca: "Carnes blancas",
      tiempo: "Tiempo (min)",
      porciones: "Porciones",
      limpiar: "Limpiar filtros",
      notFoundTitle: "Página no encontrada",
      save: "Guardar",
      update: "Actualizar Receta",
      image: "URL de la imagen",
      notFoundMessage: "Parece que te has perdido buscando ingredientes.",
      backToHome: "Volver al inicio",
      email: "ejemplo@correo.com",
      password: "Tu contraseña",
      ingredients: "Ejemplo: 2 huevos, 200g de harina, 1 taza de leche"
    },
  },
  en: {
    loading: "Cooking recipes",
    recipeBook: "Recipe Book 007",
    favorites: "Favorites",
    home: "Home",
    filters: "Filters",
    sinFavoritos: "There are no favorites to show.",
    noReceta: "Loading recipes...",
    error: "Error loading information...",
    description: "Description",
    gluten: "Free gluten",
    preparation: "Preparation",
    noInfo: "No information available",
    notFoundTitle: "Page Not Found",
    notFoundMessage: "It seems you got lost looking for ingredients.",
    backToHome: "Back to home",
    createRecipe: "Create New Recipe",
    editRecipe: "Edit Recipe",
    loginTitle: "Login",
    emailLabel: "Email Address",
    passwordLabel: "Password",
    noPass: "Forgot your password?",
    loginButton: "Sign In",
    logoutQuestion: "Do you want to log out?",
    confirmYes: "Yes",
    confirmNo: "No",
    registerButton: "Register",
    siCuenta: "you have account?",
    noCuenta: "you don't have an account?",
    createAccount: "Create",
    notAccess: "Restricted access",
    messAccess: "To do that, please log in",
    messRol:"Your user account does not have the necessary privileges to view this page",
    placeHolder: {
      titulo: "Title",
      ingredientes: "Ingredients",
      todo: "All",
      vegano: "Vegan",
      vegetariano: "Vegetarian",
      carneRoja: "Red Meat",
      carneBlanca: "White Meat",
      tiempo: "Time (min)",
      porciones: "Portions",
      limpiar: "Clean filters",
      notFoundTitle: "Not found",
      save: "Save",
      update: "Update Recipe",
      image: "Image URL",
      notFoundMessage: "It seems you got lost looking for ingredients.",
      backToHome: "Back to top",
      email: "example@mail.com",
      password: "Your password",
      ingredients: "Example: 2 eggs, 200g of flour, 1 cup of milk"
    },
  },
};
