export const texts = {
  es: {
    favorites: "Favoritos",
    home: "Inicio",
    filters: "Filtros",
    sinFavoritos: "No existen favoritos para mostrar.",
    noReceta: "Cargando recetas...",
    error: "Error al cargar la información...",
    description: "Descripción",
    gluten: "Sin gluten",
    preparation: "Preparación",
    noInfo: "No existe información disponible",
    notFoundTitle: "Página no encontrada",
    notFoundMessage: "Parece que te has perdido buscando ingredientes.",
    backToHome: "Volver al inicio",
    placeHolder: {
      titulo: "Titulo",
      ingredientes: "Ingredientes",
      todo: "Todos",
      vegano: "Vegano",
      vegetariano: "Vegetariano",
      carneRoja: "Carnes rojas",
      carneBlanca: "Carnes blancas",
      tiempo: "Tiempo (min)",
      porciones: "Porciones",
      limpiar: "Limpiar filtros",
      notFoundTitle: "Página no encontrada",
    notFoundMessage: "Parece que te has perdido buscando ingredientes.",
    backToHome: "Volver al inicio",
    }
  },
  en: {
    favorites: "Favorites",
    home: "Home",
    filters: "Filters",
    sinFavoritos: "There are no favorites to show.",
    noReceta: "Loading recipes...",
    error: "Error loading information...",
    description: "Description",
    gluten: "Free gluten",
    preparation: "Preparation",
    noInfo: "No information available",
    notFoundTitle: "Page Not Found",
    notFoundMessage: "It seems you got lost looking for ingredients.",
    backToHome: "Back to Home",
    placeHolder: {
      titulo: "Title",
      ingredientes: "Ingredients",
      todo: "All",
      vegano: "Vegan",
      vegetariano: "Vegetarian",
      carneRoja: "Red meat",
      carneBlanca: "White meat",
      tiempo: "Time (min)",
      porciones: "Portions",
      limpiar: "Clean filters",
      
    }
  },
};

//acá voy agregando los títulos, textos de botones etc para tenerlos en ambos idiomas
